const arrayCards = [
  {
    src: "./img/web-pizzaria.png",
    title: "Pizzaria",
    summary: "Site Pizzaria ",
    icon1: "html5",
    icon2: "css3",
    icon3: "javascript",
    icon4: "",
    icon5: "",
    icon6: "visual-studio",
    alert: "",
    deploy: "https://daliosy.github.io/pizzaria",
    repository: "https://github.com/DalioSY/pizzaria",
  },
  {
    src: "./img/web-weather-forecast.png",
    title: "Weather Forecast",
    summary: "Previsão de tempo com API ",
    icon1: "html5",
    icon2: "css3",
    icon3: "javascript",
    icon4: "",
    icon5: "",
    icon6: "visual-studio",
    alert: "",
    deploy: "https://daliosy.github.io/weather-forecast",
    repository: "https://github.com/DalioSY/weather-forecast",
  },
  {
    src: "./img/web-codeffvii.png",
    title: "Final Fantasy VII",
    summary: "Site Soldier Cloud, Zack e Sephiroth",
    icon1: "html5",
    icon2: "css3",
    icon3: "javascript",
    icon4: "",
    icon5: "",
    icon6: "visual-studio",
    alert: "",
    deploy: "https://daliosy.github.io/codeffvii",
    repository: "https://github.com/DalioSY/codeffvii",
  },
  {
    src: "./img/web-front-end-devbills.png",
    title: "Front-End DevBills",
    summary: "Site Controle financeiro pessoal",
    icon1: "typescript",
    icon2: "react",
    icon3: "",
    icon4: "",
    icon5: "",
    icon6: "visual-studio",
    alert: "sem Deploy",
    deploy: "#project",
    repository: "https://github.com/DalioSY/front-end-devbills",
  },
  {
    src: "./img/web-back-end-devbills.png",
    title: "Back-End DevBills",
    summary: "API Controle financeiro pessoal",
    icon1: "typescript",
    icon2: "nodejs",
    icon3: "",
    icon4: "",
    icon5: "",
    icon6: "visual-studio",
    alert: "sem Deploy",
    deploy: "#project",
    repository: "https://github.com/DalioSY/back-end-codebills",
  },
  {
    src: "./img/web-front-end-codeburger.png",
    title: "Front-End CodeBurguer",
    summary: "Site e-commerce de uma hamburgueria",
    icon1: "",
    icon2: "",
    icon3: "javascript",
    icon4: "react",
    icon5: "",
    icon6: "visual-studio",
    alert: "sem Deploy",
    deploy: "#project",
    repository: "https://github.com/DalioSY/front-end-codeburger",
  },
  {
    src: "./img/web-back-end-codeburger.png",
    title: "Back-End CodeBurguer",
    summary: "API e-commerce de uma hamburgueria",
    icon1: "javascript",
    icon2: "nodejs ",
    icon3: "postgresql",
    icon4: "mongodb",
    icon5: "docker",
    icon6: "visual-studio",
    alert: "sem Deploy",
    deploy: "#project",
    repository: "https://github.com/DalioSY/back-end-codeburger",
  },
  {
    src: "./img/web-cake-house.png",
    title: "Cake House",
    summary: "Site Casa de Bolo",
    icon1: "html5",
    icon2: "css3",
    icon3: "javascript",
    icon4: "",
    icon5: "",
    icon6: "visual-studio",
    alert: "",
    deploy: "https://daliosy.github.io/cake-house",
    repository: "https://github.com/DalioSY/cake-house",
  },
  {
    src: "./img/web-cafeteria.png",
    title: "Cafeteria",
    summary: "Site Cafeteria",
    icon1: "html5",
    icon2: "css3",
    icon3: "javascript",
    icon4: "",
    icon5: "",
    icon6: "visual-studio",
    alert: "",
    deploy: "https://daliosy.github.io/cafeteria",
    repository: "https://github.com/DalioSY/cafeteria",
  },
  {
    src: "./img/web-login.png",
    title: "Login",
    summary: "Tela de login ",
    icon1: "html5",
    icon2: "css3",
    icon3: "javascript",
    icon4: "",
    icon5: "",
    icon6: "visual-studio",
    alert: "",
    deploy: "https://daliosy.github.io/login",
    repository: "https://github.com/DalioSY/login",
  },
  {
    src: "./img/web-clima.png",
    title: "CLIMA TEMPO",
    summary: "Previsão do tempo real",
    icon1: "html5",
    icon2: "css3",
    icon3: "javascript",
    icon4: "",
    icon5: "",
    icon6: "visual-studio",
    alert: "",
    deploy: "https://daliosy.github.io/clima-tempo",
    repository: "https://github.com/DalioSY/clima-tempo",
  },
  {
    src: "./img/web-mario.png",
    title: "MARIO BROS",
    summary: "Site Mario Bros",
    icon1: "html5",
    icon2: "css3",
    icon3: "javascript",
    icon4: "",
    icon5: "",
    icon6: "visual-studio",
    alert: "",
    deploy: "https://daliosy.github.io/mario",
    repository: "https://github.com/DalioSY/mario",
  },
  {
    src: "./img/web-starbucks.png",
    title: "Starbucks",
    summary: "Site Starbucks",
    icon1: "html5",
    icon2: "css3",
    icon3: "javascript",
    icon4: "",
    icon5: "",
    icon6: "visual-studio",
    alert: "",
    deploy: "https://daliosy.github.io/starbucks",
    repository: "https://github.com/DalioSY/starbucks",
  },
  {
    src: "./img/web-register.png",
    title: "CADASTRO DE USUÁRIOS",
    summary: "Cadastro de Nome e idade",
    icon1: "html5",
    icon2: "css3",
    icon3: "javascript",
    icon4: "react",
    icon5: "",
    icon6: "visual-studio",
    alert: "",
    deploy: "https://project-react-sigma.vercel.app/",
    repository: "https://github.com/DalioSY/react-1",
  },
  {
    src: "./img/web-cronometro.png",
    title: "CRONÔMETRO",
    summary: "Cronômetro simples",
    icon1: "html5",
    icon2: "css3",
    icon3: "javascript",
    icon4: "",
    icon5: "",
    icon6: "visual-studio",
    alert: "",
    deploy: "https://daliosy.github.io/cronometro/",
    repository: "https://github.com/DalioSY/cronometro/",
  },
  {
    src: "./img/web-calculadora.png",
    title: "Calculadora",
    summary: "Calculadora simples",
    icon1: "html5",
    icon2: "css3",
    icon3: "javascript",
    icon4: "",
    icon5: "",
    icon6: "visual-studio",
    alert: "",
    deploy: "https://daliosy.github.io/calculadora/",
    repository: "https://github.com/DalioSY/calculadora/",
  },
  {
    src: "./img/web-convert.png",
    title: "PROJECT CONVERT MONEY",
    summary: "Convertor de moeda em tempo real ",
    icon1: "html5",
    icon2: "css3",
    icon3: "javascript",
    icon4: "",
    icon5: "",
    icon6: "visual-studio",
    alert: "",
    deploy: "https://daliosy.github.io/convert-money/",
    repository: "https://github.com/DalioSY/convert-money/",
  },
  {
    src: "./img/web-randon.png",
    title: "RANDON",
    summary: "Sorteio entre dois numeros ",
    icon1: "html5",
    icon2: "css3",
    icon3: "javascript",
    icon4: "",
    icon5: "",
    icon6: "visual-studio",
    alert: "",
    deploy: "https://daliosy.github.io/random/",
    repository: "https://github.com/DalioSY/random/",
  },
  {
    src: "./img/web-hashiras.png",
    title: "Hashiras",
    summary: "Anime Demon Slayer mosntra todos os hashiras",
    icon1: "html5",
    icon2: "css3",
    icon3: "javascript",
    icon4: "",
    icon5: "",
    icon6: "visual-studio",
    alert: "",
    deploy: "https://daliosy.github.io/hashira/",
    repository: "https://github.com/DalioSY/hashira",
  },
  {
    src: "./img/web-burger.png",
    title: "BURGER",
    summary:
      "Projeto de estudo para fazer descontos, filtar e soma valor total ",
    icon1: "html5",
    icon2: "css3",
    icon3: "javascript",
    icon4: "",
    icon5: "",
    icon6: "visual-studio",
    alert: "",
    deploy: "https://daliosy.github.io/burger",
    repository: "https://github.com/DalioSY/burger",
  },
  {
    src: "./img/web-nodejr.png",
    title: "NODE.JS",
    summary: "Projeto de estudo usando funções get, post, put e delete",
    icon1: "nodejs",
    icon2: "",
    icon3: "",
    icon4: "",
    icon5: "",
    icon6: "visual-studio",
    alert: "sem Deploy",
    deploy: "#project",
    repository: "https://github.com/DalioSY/node-js",
  },
];
